### ISSUE TITLE
Question posed that isn't answered in the reference text

### ISSUE THREAD

**Issue by murtyjones** [chaincodelabs/study-groups#41]
Question 9 in the [intro section](https://github.com/chaincodelabs/study-groups/tree/master/welcome-to-the-bitcoin-protocol) is "What will happen when the mining reward runs out? (Bitcoin's Security Model: A Deep Dive)," but the [deep dive](https://www.coindesk.com/bitcoins-security-model-deep-dive) doesn't make reference to this topic directly.

There is a link to a blog post by Arvind Narayanan discussing Bitcoin in the absence of the block reward. Is the intent that the reader should click through to read that post? I'd suggest adding this reading as its own link in the syllabus.
> In practice, this has held true throughout bitcoin’s history due to miner incentives, though [some question](https://freedom-to-tinker.com/2016/10/21/bitcoin-is-unstable-without-the-block-reward/) if it will continue to hold true in the future.

I think a good question for the security deep dive would be something along the lines of "What is Sybil Resistance and how does proof of work make Bitcoin Sybil Resistant for new nodes?"

**Comment by adamjonas** [comment]
Hey @murtyjones - you are quite right. It's not directly addressed, but I think the point is to spur discussion rather than have an "answer." I invite you to open a PR to add any relevant discussion questions though. I think "What is Sybil Resistance and how does proof of work make Bitcoin Sybil Resistant for new nodes?" is a good one.

**Comment by murtyjones** [comment]
Sounds good – proposed some questions and example answers for the intro section in #42
